networks:
  anu-network:
    name: anu-network
    driver: bridge

services:
  auth:
    build: .
    container_name: anu-auth
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=3000"
    networks:
      - anu-network
